repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: venv/Scripts/pylint.exe
        language: system
        types: [python]
        args:
          [
            "-rn", 
            "-sn", 
            "--rcfile=.pylintrc", 
            "--load-plugins=pylint.extensions.docparams", 
          ]
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: 'venv/Scripts/pip.exe freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]